services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/server-jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider'
    volumes:
      - ./cert/server-jaas.conf:/etc/kafka/server-jaas.conf:ro,z

  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
      - '9092:9092'
      - '29093:29093'
      - '9093:9093'
      - '29094:29094'
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: '0'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL,SSL_HOST:SSL,SASL_SSL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092,SSL://kafka1:29093,SSL_HOST://localhost:9093,SASL_SSL://kafka1:29094,SASL_SSL_HOST://localhost:9094
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_NUM_PARTITIONS: '2'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
      KAFKA_SSL_KEYSTORE_FILENAME: 'kafka.server.keystore.jks'
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 'keystore_creds'
      KAFKA_SSL_KEY_CREDENTIALS: 'sslkey_creds'
      KAFKA_SSL_TRUSTSTORE_FILENAME: 'kafka.server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 'truststore_creds'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN,SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_OPTS: '-Djava.security.auth.login.config=/opt/kafka/config/server-jaas.conf'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    volumes:
      - ./cert/kafka.server.keystore.jks:/etc/kafka/secrets/kafka.server.keystore.jks:ro,z
      - ./cert/kafka.server.truststore.jks:/etc/kafka/secrets/kafka.server.truststore.jks:ro,z
      - ./cert/keystore_creds:/etc/kafka/secrets/keystore_creds:ro,z
      - ./cert/sslkey_creds:/etc/kafka/secrets/sslkey_creds:ro,z
      - ./cert/truststore_creds:/etc/kafka/secrets/truststore_creds:ro,z
      - ./cert/server-jaas.conf:/opt/kafka/config/server-jaas.conf:ro,z